//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/RocketInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RocketInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RocketInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RocketInput"",
    ""maps"": [
        {
            ""name"": ""flying"",
            ""id"": ""65e2e9f2-5bc6-4517-a703-757ace9f3817"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""9ce40467-7710-4025-bfd6-5ea7aacae2b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""71752a3e-cba5-4f9a-9b82-f855acf54bc5"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9019468f-0752-47f5-a13c-ccc67f006ffd"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WS"",
                    ""id"": ""e57df4d8-24c5-4b86-ac2a-4eb7818f86d2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""75091f62-8012-49e0-95e0-c2471ff88735"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""d8741dea-d48d-4090-b87e-b365a350f1a9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""flying_2d"",
            ""id"": ""1b6be978-9c58-4ae0-8c0d-3bdd03cce7ba"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Button"",
                    ""id"": ""cfff3625-0609-4ba8-a037-7eab6eee217c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Verticle"",
                    ""id"": ""9e3560df-daa3-4c44-ae19-166bc8d172b3"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""81a27b30-7a50-4064-a3db-ab22faf6e0a3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1ebee8c4-f88f-4366-9a7c-8a82feffa937"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // flying
        m_flying = asset.FindActionMap("flying", throwIfNotFound: true);
        m_flying_Movement = m_flying.FindAction("Movement", throwIfNotFound: true);
        m_flying_Rotation = m_flying.FindAction("Rotation", throwIfNotFound: true);
        // flying_2d
        m_flying_2d = asset.FindActionMap("flying_2d", throwIfNotFound: true);
        m_flying_2d_Movement = m_flying_2d.FindAction("Movement", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // flying
    private readonly InputActionMap m_flying;
    private List<IFlyingActions> m_FlyingActionsCallbackInterfaces = new List<IFlyingActions>();
    private readonly InputAction m_flying_Movement;
    private readonly InputAction m_flying_Rotation;
    public struct FlyingActions
    {
        private @RocketInput m_Wrapper;
        public FlyingActions(@RocketInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_flying_Movement;
        public InputAction @Rotation => m_Wrapper.m_flying_Rotation;
        public InputActionMap Get() { return m_Wrapper.m_flying; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FlyingActions set) { return set.Get(); }
        public void AddCallbacks(IFlyingActions instance)
        {
            if (instance == null || m_Wrapper.m_FlyingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FlyingActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
        }

        private void UnregisterCallbacks(IFlyingActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
        }

        public void RemoveCallbacks(IFlyingActions instance)
        {
            if (m_Wrapper.m_FlyingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFlyingActions instance)
        {
            foreach (var item in m_Wrapper.m_FlyingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FlyingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FlyingActions @flying => new FlyingActions(this);

    // flying_2d
    private readonly InputActionMap m_flying_2d;
    private List<IFlying_2dActions> m_Flying_2dActionsCallbackInterfaces = new List<IFlying_2dActions>();
    private readonly InputAction m_flying_2d_Movement;
    public struct Flying_2dActions
    {
        private @RocketInput m_Wrapper;
        public Flying_2dActions(@RocketInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_flying_2d_Movement;
        public InputActionMap Get() { return m_Wrapper.m_flying_2d; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Flying_2dActions set) { return set.Get(); }
        public void AddCallbacks(IFlying_2dActions instance)
        {
            if (instance == null || m_Wrapper.m_Flying_2dActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Flying_2dActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
        }

        private void UnregisterCallbacks(IFlying_2dActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
        }

        public void RemoveCallbacks(IFlying_2dActions instance)
        {
            if (m_Wrapper.m_Flying_2dActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFlying_2dActions instance)
        {
            foreach (var item in m_Wrapper.m_Flying_2dActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Flying_2dActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Flying_2dActions @flying_2d => new Flying_2dActions(this);
    public interface IFlyingActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
    }
    public interface IFlying_2dActions
    {
        void OnMovement(InputAction.CallbackContext context);
    }
}
